# Generated by Django 4.2.30 on 2026-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('POS Issue', 'POS Issue'), ('Delivery Delay', 'Delivery Delay'), ('Inventory', 'Inventory'), ('Kitchen Equipment', 'Kitchen Equipment'), ('Customer Complaint', 'Customer Complaint'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_suggested_action', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
    ]
